In [4]:
import numpy as np
from typing import Tuple, Generator, Iterator

In [5]:
class ColumnBunches4():
    
    def __init__(self, data: np.ndarray, window: int, skip_diag=False):
        
        self.data = data
        N = data.shape[1]
        self.w = window
        self.sd = int(skip_diag)
        
        self.M = (N-1) // self.w + 1
        
        # I, J, K indeces identify bunches of w columns
        # they sit in range(0:M-1)
        self.IJKL = self._IJKL_gen()
        self.IJKL_diag = self._IJKL_diag_gen()
        
    def _IJKL_gen(self) -> Generator:
        for I in range(self.M):
            for J in range(I + self.sd, self.M):
                for K in range(J + self.sd, self.M):
                    for L in range(K + self.sd, self.M):
                        yield I, J, K, L
                
    def _IJKL_diag_gen(self) -> Generator:
        for I in range(self.M):
            for J in range(I, self.M):
                for K in range(J, self.M):
                    for L in range(K, self.M):
                        if len({I, J, K, L}) < 4:
                            yield I, J, K, L
    
    def _get_columns(self, indeces) -> Tuple:
        return [self.data[:,self.w*idx : self.w*(idx+1)] for idx in indeces]
    
    def __next__(self) -> Tuple:
        return self._get_columns(next(self.IJKL))
    
    def __iter__(self) -> Iterator:
        return self
    
    def next_diag(self) -> Tuple:
        return self._get_columns(next(self.IJKL_diag))

In [6]:
M1 = np.array([list(range(10))]*2)
M1

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [7]:
# get all column bunches (diagonal and non-diagonal)

bunches = ColumnBunches4(M1, window=3)

for bunch in bunches:
    for columns in bunch:
        print(columns)
    print(">-------")

[[0 1 2]
 [0 1 2]]
[[0 1 2]
 [0 1 2]]
[[0 1 2]
 [0 1 2]]
[[0 1 2]
 [0 1 2]]
>-------
[[0 1 2]
 [0 1 2]]
[[0 1 2]
 [0 1 2]]
[[0 1 2]
 [0 1 2]]
[[3 4 5]
 [3 4 5]]
>-------
[[0 1 2]
 [0 1 2]]
[[0 1 2]
 [0 1 2]]
[[0 1 2]
 [0 1 2]]
[[6 7 8]
 [6 7 8]]
>-------
[[0 1 2]
 [0 1 2]]
[[0 1 2]
 [0 1 2]]
[[0 1 2]
 [0 1 2]]
[[9]
 [9]]
>-------
[[0 1 2]
 [0 1 2]]
[[0 1 2]
 [0 1 2]]
[[3 4 5]
 [3 4 5]]
[[3 4 5]
 [3 4 5]]
>-------
[[0 1 2]
 [0 1 2]]
[[0 1 2]
 [0 1 2]]
[[3 4 5]
 [3 4 5]]
[[6 7 8]
 [6 7 8]]
>-------
[[0 1 2]
 [0 1 2]]
[[0 1 2]
 [0 1 2]]
[[3 4 5]
 [3 4 5]]
[[9]
 [9]]
>-------
[[0 1 2]
 [0 1 2]]
[[0 1 2]
 [0 1 2]]
[[6 7 8]
 [6 7 8]]
[[6 7 8]
 [6 7 8]]
>-------
[[0 1 2]
 [0 1 2]]
[[0 1 2]
 [0 1 2]]
[[6 7 8]
 [6 7 8]]
[[9]
 [9]]
>-------
[[0 1 2]
 [0 1 2]]
[[0 1 2]
 [0 1 2]]
[[9]
 [9]]
[[9]
 [9]]
>-------
[[0 1 2]
 [0 1 2]]
[[3 4 5]
 [3 4 5]]
[[3 4 5]
 [3 4 5]]
[[3 4 5]
 [3 4 5]]
>-------
[[0 1 2]
 [0 1 2]]
[[3 4 5]
 [3 4 5]]
[[3 4 5]
 [3 4 5]]
[[6 7 8]
 [6 7 8]]
>-------
[[0 1 2]
 [0 1 2]]
[

In [8]:
# get 'non-diagonal' (yellow) bunches only

bunches = ColumnBunches4(M1, window=3, skip_diag=True)

for bunch in bunches:
    for columns in bunch:
        print(columns)
    print(">-------")

[[0 1 2]
 [0 1 2]]
[[3 4 5]
 [3 4 5]]
[[6 7 8]
 [6 7 8]]
[[9]
 [9]]
>-------


In [9]:
# get 'diagonal' (blue) bunches only

bunches = ColumnBunches4(M1, window=3, skip_diag=True)

while True:
    try:
        bunch = bunches.next_diag()
        for columns in bunch:
            print(columns)
        print(">-------")
    except:
        break

[[0 1 2]
 [0 1 2]]
[[0 1 2]
 [0 1 2]]
[[0 1 2]
 [0 1 2]]
[[0 1 2]
 [0 1 2]]
>-------
[[0 1 2]
 [0 1 2]]
[[0 1 2]
 [0 1 2]]
[[0 1 2]
 [0 1 2]]
[[3 4 5]
 [3 4 5]]
>-------
[[0 1 2]
 [0 1 2]]
[[0 1 2]
 [0 1 2]]
[[0 1 2]
 [0 1 2]]
[[6 7 8]
 [6 7 8]]
>-------
[[0 1 2]
 [0 1 2]]
[[0 1 2]
 [0 1 2]]
[[0 1 2]
 [0 1 2]]
[[9]
 [9]]
>-------
[[0 1 2]
 [0 1 2]]
[[0 1 2]
 [0 1 2]]
[[3 4 5]
 [3 4 5]]
[[3 4 5]
 [3 4 5]]
>-------
[[0 1 2]
 [0 1 2]]
[[0 1 2]
 [0 1 2]]
[[3 4 5]
 [3 4 5]]
[[6 7 8]
 [6 7 8]]
>-------
[[0 1 2]
 [0 1 2]]
[[0 1 2]
 [0 1 2]]
[[3 4 5]
 [3 4 5]]
[[9]
 [9]]
>-------
[[0 1 2]
 [0 1 2]]
[[0 1 2]
 [0 1 2]]
[[6 7 8]
 [6 7 8]]
[[6 7 8]
 [6 7 8]]
>-------
[[0 1 2]
 [0 1 2]]
[[0 1 2]
 [0 1 2]]
[[6 7 8]
 [6 7 8]]
[[9]
 [9]]
>-------
[[0 1 2]
 [0 1 2]]
[[0 1 2]
 [0 1 2]]
[[9]
 [9]]
[[9]
 [9]]
>-------
[[0 1 2]
 [0 1 2]]
[[3 4 5]
 [3 4 5]]
[[3 4 5]
 [3 4 5]]
[[3 4 5]
 [3 4 5]]
>-------
[[0 1 2]
 [0 1 2]]
[[3 4 5]
 [3 4 5]]
[[3 4 5]
 [3 4 5]]
[[6 7 8]
 [6 7 8]]
>-------
[[0 1 2]
 [0 1 2]]
[