In [4]:
import numpy as np
from typing import Tuple, Generator, Iterator

In [20]:
class ColumnBunches4():
    
    def __init__(self, data: np.ndarray, window: int, get_diag=True, diag_only=False):
        self.data = data
        self.N = data.shape[1]
        self.w = window # m
        self.gd = int(get_diag)
        self.IJKL = self._IJKL_gen() if not diag_only else self._IJKL_diag_gen()
        
    def _IJKL_gen(self) -> Generator:
        for I in range(1 - self.gd, (self.N-1) // self.w + 1):
            for J in range(I + self.gd):
                for K in range(J + self.gd):
                    for L in range(K + self.gd):
                        yield I, J, K, L
                
    def _IJKL_diag_gen(self) -> Generator:
        for I in range((self.N-1) // self.w + 1):
            for J in range(I + 1):
                for K in range(I - J + 1):
                    yield I, J, K, I - J - K
    
    def _get_columns(self, I: int, J: int, K: int, L: int) -> Tuple:
        return self.data[:, self.w*I : self.w*(I+1)], \
               self.data[:, self.w*J : self.w*(J+1)], \
               self.data[:, self.w*K : self.w*(K+1)], \
               self.data[:, self.w*L : self.w*(L+1)]
    
    def __next__(self) -> Tuple:
        return self._get_columns(*next(self.IJKL))
    
    def __iter__(self) -> Iterator:
        return self

In [21]:
M1 = np.array([[1.,2,3,4,5]]*3)
M1

array([[1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.]])

In [26]:
bunches = ColumnBunches4(M1, window=3)

for bunch in bunches:
    for column in bunch:
        print(column)
    print(">-------")

[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]
[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]
[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]
[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]
>-------
[[4. 5.]
 [4. 5.]
 [4. 5.]]
[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]
[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]
[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]
>-------
[[4. 5.]
 [4. 5.]
 [4. 5.]]
[[4. 5.]
 [4. 5.]
 [4. 5.]]
[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]
[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]
>-------
[[4. 5.]
 [4. 5.]
 [4. 5.]]
[[4. 5.]
 [4. 5.]
 [4. 5.]]
[[4. 5.]
 [4. 5.]
 [4. 5.]]
[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]
>-------
[[4. 5.]
 [4. 5.]
 [4. 5.]]
[[4. 5.]
 [4. 5.]
 [4. 5.]]
[[4. 5.]
 [4. 5.]
 [4. 5.]]
[[4. 5.]
 [4. 5.]
 [4. 5.]]
>-------


In [28]:
bunches = ColumnBunches4(M1, window=3, diag_only=True)
list(bunches._IJKL_diag_gen())

[(0, 0, 0, 0), (1, 0, 0, 1), (1, 0, 1, 0), (1, 1, 0, 0)]

In [27]:
bunches = ColumnBunches4(M1, window=3, diag_only=True)

for bunch in bunches:
    for column in bunch:
        print(column)
    print(">-------")

[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]
[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]
[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]
[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]
>-------
[[4. 5.]
 [4. 5.]
 [4. 5.]]
[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]
[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]
[[4. 5.]
 [4. 5.]
 [4. 5.]]
>-------
[[4. 5.]
 [4. 5.]
 [4. 5.]]
[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]
[[4. 5.]
 [4. 5.]
 [4. 5.]]
[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]
>-------
[[4. 5.]
 [4. 5.]
 [4. 5.]]
[[4. 5.]
 [4. 5.]
 [4. 5.]]
[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]
[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]
>-------
